package enums;

public enum State {
    INIT,
    LOGGING_IN_AS_ADMIN,
    LOGGING_IN_AS_ACCOUNTANT,
    LOGGED_IN_AS_ADMIN,
    LOGGED_IN_AS_ACCOUNTANT,
    MANAGING_ADMINS,
    CREATING_COMPANY,
    EXIT,
}
